### PR TITLE
Various Improvements

### PR DESCRIPTION
**Pull request by hbirler**
Hi! I recently discovered this project as I wanted just a solution like this to play a really old game with a couple of friends. It is great! I also wanted to improve on a couple of things, so that is what this pull request is about.

image

* Build
  * Building with VS 2022 failed since the `CMAKE_GENERATOR_PLATFORM` flag was not supported. I now use `CMAKE_SIZEOF_VOID_P` instead.
* UI
  * Streamlined the UI. There is now only one window. Launching the app connects to discord directly and can accept invites. 
  * Can leave, join, and host lobbies without closing and reopening the app.
* Fixes
  * The mapping from IPs to peers was not used before, if I understood the code correctly. This resulted in every packet being broadcasted which is both inefficient and may potentially break games that don't do much checks.
* Performance
  * Removed the `std::vector<uint8_t>` allocations when reading and writing packets. Only the WinTun allocation functions are used. Data is also not copied unnecessarily.
  * Mapping IPs to peers now only takes 2 array lookups instead of a std::map lookup (std::map uses red-black trees which are certainly slower than arrays). This is possible since the range of IPs we allocate is small and can fit in an array.

### CODE REVIEW

**Comment by gyf304** [comment]
Hi hbirler, thank you for the PR and general interest in this project. Based on a quick scan, I think your changes look good. Would you mind fixing the GitHub CI since it's currently not building?

**Comment by hbirler** [comment]
It seems that the error is in wxWidgets
```
2021-12-20T03:22:57.9850862Z D:\a\lpvpn\lpvpn\build\_deps\wxwidgets-src\src\propgrid\props.cpp(2205,54): error C2445: result type of conditional expression is ambiguous: types 'const char [20]' and 'wxString' can be converted to multiple common types [D:\a\lpvpn\lpvpn\build\build\_deps\wxwidgets-src\libs\wxmono.vcxproj]
2021-12-20T03:22:57.9858825Z D:\a\lpvpn\lpvpn\build\_deps\wxwidgets-src\src\propgrid\props.cpp(2205,54): message : could be 'const char *' [D:\a\lpvpn\lpvpn\build\build\_deps\wxwidgets-src\libs\wxmono.vcxproj]
2021-12-20T03:22:57.9865489Z D:\a\lpvpn\lpvpn\build\_deps\wxwidgets-src\src\propgrid\props.cpp(2205,54): message : or       'wxString' [D:\a\lpvpn\lpvpn\build\build\_deps\wxwidgets-src\libs\wxmono.vcxproj]
```
Weird. Maybe its a C++20 deprecation thing.

**Comment by hbirler** [comment]
If seems that the issue might be related to this https://stackoverflow.com/a/67845620

**Comment by hbirler** [comment]
The issue should be resolved now

**Comment by gyf304** [comment]
Thanks hbirler!

**Pull request merged**
